# Generated by Django 4.0.4 on 2022-04-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('done', models.BooleanField(default=False)),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Date & Time')),
            ],
        ),
    ]
